language: r
dist: trusty
cache: packages
sudo: required

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - r-cran-rjava
      - libv8-dev 
      - libmagick++-dev

r_binary_packages:
 - rgdal
