language: r
cache: packages
sudo: required

repos: 
  CRAN: https://cran.rstudio.com
  rforge: http://R-Forge.R-project.org

before_install:
  - R -e 'install.packages("rgdal", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'


r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - r-cran-rjava
      - libv8-dev 
      - libmagick++-dev

r_binary_packages:
 - rgdal