language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'
  
install:
  - export GDAL_DATA=/home/vagrant/miniconda/share/gdal/
  
  
env:
   global:
     - R_LIBS="https://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - BOOTSTRAP_LATEX=""

