language: r

sudo: required

r_binary_packages:
 - testthat
 - rgdal

r_packages:
  - XML
  - geosphere
  - fields
  - maptools
  - sp
  - maps
  - raster

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'
  
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libudunits2-dev libproj-dev libgeos-dev libgdal-dev libhdf5-serial-dev libgdal1h
